<?php
namespace Propeller\Includes\Enum;

if ( ! defined( 'ABSPATH' ) ) exit;

class Permission {
    const LISTFOLDER_READDATA = 'LISTFOLDER_READDATA';
    const READATTRIBUTES = 'READATTRIBUTES';
    const WRITEATTRIBUTES = 'WRITEATTRIBUTES';
    const DETESUBFOLDERSANDFILES = 'DETESUBFOLDERSANDFILES';
    const DELETE = 'DELETE';
    const READPERMISSIONS = 'READPERMISSIONS';
    const CHANGEPERMISSIONS = 'CHANGEPERMISSIONS';
    const TAKEOWNERSHIP = 'TAKEOWNERSHIP';
    const CREATEOBJECT_WRITEDATA = 'CREATEOBJECT_WRITEDATA';
}